trigger:
- master
- develop

variables:
  sdk_version: 2.2.300
  dockerRepositoryRoot: sannel
  dockerRepositoryName: house.openfaasrunner
  dockerTagBase: $(Build.SourceBranchName)-$(Build.BuildId)
  imageName: $(dockerRepositoryRoot)/$(dockerRepositoryName):$(dockerTagBase)
  projectFolder: Sannel.House.OpenFaasRunner
  mainProjectPath: src/$(projectFolder)/$(projectFolder).csproj
  mainConfigPath: src/$(projectFolder)/app_config
  tag: 2.2
  codeName: bionic
  hasClient: false
  hasTests: true
  disableLinux: false
  disableWindows: false
  disableOSX: false

name: $(date:yyyy.MM.dd)$(rev:.rr)

jobs:
- job: linux_arm
  pool:
    vmImage: ubuntu-16.04
  condition: ne(variables['disableLinux'], 'true')
  steps:
    - powershell: |
        # Write your commands here
        sudo apt-get update
        sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support
        Copy-Item -Verbose /usr/bin/qemu-arm-static .
        # Use the environment variables input below to pass secret variables to this script
      displayName: 'Install qemu'
    - task: Docker@1
      displayName: 'Run an image '
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Run an image'
        arguments: '--rm --privileged'
        imageName: ' multiarch/qemu-user-static:register'
        containerCommand: '--reset'
    - task: Docker@0
      displayName: 'Build an src arm'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'Docker Hub'
        dockerFile: 'build/linux_arm/Dockerfile.src'
        buildArguments: 'tag=$(tag)-$(codeName)-arm32v7'
        defaultContext: false
        imageName: '$(imageName)-linux-src-arm32v7'
    - task: Docker@0
      displayName: 'Build an image arm'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'Docker Hub'
        dockerFile: 'build/linux_arm/Dockerfile'
        buildArguments: 'tag=$(tag)-$(codeName)-arm32v7'
        defaultContext: false
        context: '$(Build.StagingDirectory)'
        imageName: '$(imageName)-linux-arm32v7'
    - powershell: |
        $img = "$(imageName)".ToLower()
        docker save -o $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm32v7.tar "${img}-linux-arm32v7"
        docker save -o $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm32v7.src.tar "${img}-linux-src-arm32v7"
        tar cvf $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm.tar $(Build.StagingDirectory)/*.tar
        bzip2 -9 $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm.tar
      displayName: 'export image'
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: 'linux-arm'
        targetPath: '$(Build.StagingDirectory)'
